### ISSUE TITLE
Allow for use of import es6 syntax (with Gulp)

### ISSUE THREAD

**Issue by dannyjlaurence** [Bjornej/GruntLauncher#47]
My gulp file includes the following: 

``` javascript
import gulp from "gulp";
import modernWebDevBuild from "modern-web-dev-build";
let options = {};

modernWebDevBuild.registerTasks(gulp, options);
```

Which throws the following error: 

```
import gulp from "gulp";
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (C:\Users\584020\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\584020\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\584020\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)
```

I presume that this has to do with parsing the import statement. Let me know if it's a quick fix, I can open a pull request if you give me a little guidance.

**Comment by dannyjlaurence** [comment]
Ah - I think this is a me problem. The project I'm working with uses babel to make a gulpfile - I'll go ahead and close it
